[[contact]]
name = "Address"
address = "1430 2nd Ave. Seattle, WA 98109"
icon = "fa-map-marked-alt"
[[contact]]
name = "Email"
address = """<a href="#!">hello@cloudcast.consulting</a>"""
icon = "fa-envelope"
[[contact]]
name = "Email "
address = """<a href="#!">hello@cloudcast.consulting</a>"""
icon = "fa-paper-plane-top"
[[social]]
icon = "fa-mastodon"
url = "#!"
[[social]]
icon = "fa-aws"
url = "#!"
[[social]]
icon = "fa-github"
url = "https://github.com/r6t/cloudcast-dot-consulting"
