[[contact]]
name = "Address"
address = "1430 2nd Ave. Seattle, WA 98109"
icon = "fa-map-marked-alt"
[[contact]]
name = "Email"
address = """<a href="#!">hello@cloudcast.consulting</a>"""
icon = "fa-envelope"
[[contact]]
name = "Phone"
address = "+1 (555) 902-8832"
icon = "fa-mobile-alt"
[[social]]
icon = "fa-mastodon"
url = "#!"
[[social]]
icon = "fa-aws"
url = "#!"
[[social]]
icon = "fa-github"
url = "https://github.com/mattimustang/zola-grayscale"
