[[contact]]
name = "Mail"
address = "415 1st Ave N, Unit 19472<br>Seattle, WA 98109"
icon = "fa-building-o"
[[contact]]
name = "Email"
icon = "fa-paper-plane-top"
content = """
<a href="mailto:hello@cloudcast.consulting">hello@cloudcast.consulting</a>
<br><br>
<a href="publickey.hello.asc">PGP Public Key</a>
"""
[[contact]]
name = "AWS IQ"
icon = "fa-aws"
content = """
Work with Cloudcast from inside your AWS account on AWS IQ.
"""
