[[contact]]
name = "Mail"
address = "415 1st Ave N, Unit 19472<br>Seattle, WA 98109"
icon = "fas fa-building"
[[contact]]
name = "Email"
icon = "fas fa-paper-plane"
content = """
<a href="mailto:hello@cloudcast.consulting">hello@cloudcast.consulting</a>
<br>
<a href="publickey.hello.asc">PGP Public Key</a>
"""
[[contact]]
name = "AWS Certified"
icon = "fas fa-circle-check"
content = """
Verify AWS Certifications on <a href="https://www.credly.com/users/ryan-cast">Credly</a>
"""
